### ISSUE TITLE
Does not work with SCSS mixins

### ISSUE THREAD

**Issue by AndyOGo** [davidtheclark/stylelint-selector-bem-pattern#19]
tracked in https://github.com/postcss/postcss-bem-linter/issues/97

The following code incorrectly lints: `Invalid component selector "&:hover"`

````scss
@mixin link {
  color: blue;

  &:hover {
    color: red;
  }
}

.link {
  @include link();
}
````

**Note**
With declarative style of `Less` this is not a problem.
