### ISSUE TITLE
How do regexes work?

### ISSUE THREAD

**Issue by VinSpee** [davidtheclark/stylelint-selector-bem-pattern#9]
on the heels of the last issue, how do regexes actually get handled? I have a regex that is "working" which is still being treated as an invalid selector.

ex:

```json
"utilitySelectors": "^\\.blank-u-(?:(?:bb|sm|md|lg|gg)-)?[A-z]+$"
```

input:
`.blank-u-gg-pdVgg{}`

output:
```
Invalid utility selector ".blank-u-gg-pdVgg" (selector-bem-pattern)
```

regex test case: https://regex101.com/r/xF3xV7/1

Am I missing something?

**Comment by davidtheclark** [comment]
Did you `@define utilities` at the top of the stylesheet?

**Comment by VinSpee** [comment]
yep. 

source:

```css
/** @define utilities */

.blank-u-mgVn {
	margin-bottom: var(--blank-space-n) !important;
	margin-top: var(--blank-space-n) !important;
}

.blank-u-mgVbb {
	margin-bottom: var(--blank-space-bb) !important;
	margin-top: var(--blank-space-bb) !important;
}

.blank-u-mgVsm {
	margin-bottom: var(--blank-space-sm) !important;
	margin-top: var(--blank-space-sm) !important;
}

.blank-u-mgVmd {
	margin-bottom: var(--blank-space-md) !important;
	margin-top: var(--blank-space-md) !important;
}

.blank-u-mgVlg {
	margin-bottom: var(--blank-space-lg) !important;
	margin-top: var(--blank-space-lg) !important;
}

.blank-u-mgVgg {
	margin-bottom: var(--blank-space-gg) !important;
	margin-top: var(--blank-space-gg) !important;
}

.blank-u-pdVn {
	padding-bottom: var(--blank-space-n) !important;
	padding-top: var(--blank-space-n) !important;
}

.blank-u-pdVbb {
	padding-bottom: var(--blank-space-bb) !important;
	padding-top: var(--blank-space-bb) !important;
}

.blank-u-pdVsm {
	padding-bottom: var(--blank-space-sm) !important;
	padding-top: var(--blank-space-sm) !important;
}

.blank-u-pdVmd {
	padding-bottom: var(--blank-space-md) !important;
	padding-top: var(--blank-space-md) !important;
}

.blank-u-pdVlg {
	padding-bottom: var(--blank-space-lg) !important;
	padding-top: var(--blank-space-lg) !important;
}

.blank-u-pdVgg {
	padding-bottom: var(--blank-space-gg) !important;
	padding-top: var(--blank-space-gg) !important;
}

@media(--bb) {
	.blank-u-bb-mgVn {
		margin-bottom: var(--blank-space-n) !important;
		margin-top: var(--blank-space-n) !important;
	}

	.blank-u-bb-mgVbb {
		margin-bottom: var(--blank-space-bb) !important;
		margin-top: var(--blank-space-bb) !important;
	}

	.blank-u-bb-mgVsm {
		margin-bottom: var(--blank-space-sm) !important;
		margin-top: var(--blank-space-sm) !important;
	}

	.blank-u-bb-mgVmd {
		margin-bottom: var(--blank-space-md) !important;
		margin-top: var(--blank-space-md) !important;
	}

	.blank-u-bb-mgVlg {
		margin-bottom: var(--blank-space-lg) !important;
		margin-top: var(--blank-space-lg) !important;
	}

	.blank-u-bb-mgVgg {
		margin-bottom: var(--blank-space-gg) !important;
		margin-top: var(--blank-space-gg) !important;
	}

	.blank-u-bb-pdVn {
		padding-bottom: var(--blank-space-n) !important;
		padding-top: var(--blank-space-n) !important;
	}

	.blank-u-bb-pdVbb {
		padding-bottom: var(--blank-space-bb) !important;
		padding-top: var(--blank-space-bb) !important;
	}

	.blank-u-bb-pdVsm {
		padding-bottom: var(--blank-space-sm) !important;
		padding-top: var(--blank-space-sm) !important;
	}

	.blank-u-bb-pdVmd {
		padding-bottom: var(--blank-space-md) !important;
		padding-top: var(--blank-space-md) !important;
	}

	.blank-u-bb-pdVlg {
		padding-bottom: var(--blank-space-lg) !important;
		padding-top: var(--blank-space-lg) !important;
	}

	.blank-u-bb-pdVgg {
		padding-bottom: var(--blank-space-gg) !important;
		padding-top: var(--blank-space-gg) !important;
	}
}

@media(--sm) {
	.blank-u-sm-mgVn {
		margin-bottom: var(--blank-space-n) !important;
		margin-top: var(--blank-space-n) !important;
	}

	.blank-u-sm-mgVbb {
		margin-bottom: var(--blank-space-bb) !important;
		margin-top: var(--blank-space-bb) !important;
	}

	.blank-u-sm-mgVsm {
		margin-bottom: var(--blank-space-sm) !important;
		margin-top: var(--blank-space-sm) !important;
	}

	.blank-u-sm-mgVmd {
		margin-bottom: var(--blank-space-md) !important;
		margin-top: var(--blank-space-md) !important;
	}

	.blank-u-sm-mgVlg {
		margin-bottom: var(--blank-space-lg) !important;
		margin-top: var(--blank-space-lg) !important;
	}

	.blank-u-sm-mgVgg {
		margin-bottom: var(--blank-space-gg) !important;
		margin-top: var(--blank-space-gg) !important;
	}

	.blank-u-sm-pdVn {
		padding-bottom: var(--blank-space-n) !important;
		padding-top: var(--blank-space-n) !important;
	}

	.blank-u-sm-pdVbb {
		padding-bottom: var(--blank-space-bb) !important;
		padding-top: var(--blank-space-bb) !important;
	}

	.blank-u-sm-pdVsm {
		padding-bottom: var(--blank-space-sm) !important;
		padding-top: var(--blank-space-sm) !important;
	}

	.blank-u-sm-pdVmd {
		padding-bottom: var(--blank-space-md) !important;
		padding-top: var(--blank-space-md) !important;
	}

	.blank-u-sm-pdVlg {
		padding-bottom: var(--blank-space-lg) !important;
		padding-top: var(--blank-space-lg) !important;
	}

	.blank-u-sm-pdVgg {
		padding-bottom: var(--blank-space-gg) !important;
		padding-top: var(--blank-space-gg) !important;
	}

}

@media(--md) {
	.blank-u-md-mgVn {
		margin-bottom: var(--blank-space-n) !important;
		margin-top: var(--blank-space-n) !important;
	}

	.blank-u-md-mgVbb {
		margin-bottom: var(--blank-space-bb) !important;
		margin-top: var(--blank-space-bb) !important;
	}

	.blank-u-md-mgVsm {
		margin-bottom: var(--blank-space-sm) !important;
		margin-top: var(--blank-space-sm) !important;
	}

	.blank-u-md-mgVmd {
		margin-bottom: var(--blank-space-md) !important;
		margin-top: var(--blank-space-md) !important;
	}

	.blank-u-md-mgVlg {
		margin-bottom: var(--blank-space-lg) !important;
		margin-top: var(--blank-space-lg) !important;
	}

	.blank-u-md-mgVgg {
		margin-bottom: var(--blank-space-gg) !important;
		margin-top: var(--blank-space-gg) !important;
	}

	.blank-u-md-pdVn {
		padding-bottom: var(--blank-space-n) !important;
		padding-top: var(--blank-space-n) !important;
	}

	.blank-u-md-pdVbb {
		padding-bottom: var(--blank-space-bb) !important;
		padding-top: var(--blank-space-bb) !important;
	}

	.blank-u-md-pdVsm {
		padding-bottom: var(--blank-space-sm) !important;
		padding-top: var(--blank-space-sm) !important;
	}

	.blank-u-md-pdVmd {
		padding-bottom: var(--blank-space-md) !important;
		padding-top: var(--blank-space-md) !important;
	}

	.blank-u-md-pdVlg {
		padding-bottom: var(--blank-space-lg) !important;
		padding-top: var(--blank-space-lg) !important;
	}

	.blank-u-md-pdVgg {
		padding-bottom: var(--blank-space-gg) !important;
		padding-top: var(--blank-space-gg) !important;
	}

}

@media(--lg) {
	.blank-u-lg-mgVn {
		margin-bottom: var(--blank-space-n) !important;
		margin-top: var(--blank-space-n) !important;
	}

	.blank-u-lg-mgVbb {
		margin-bottom: var(--blank-space-bb) !important;
		margin-top: var(--blank-space-bb) !important;
	}

	.blank-u-lg-mgVsm {
		margin-bottom: var(--blank-space-sm) !important;
		margin-top: var(--blank-space-sm) !important;
	}

	.blank-u-lg-mgVmd {
		margin-bottom: var(--blank-space-md) !important;
		margin-top: var(--blank-space-md) !important;
	}

	.blank-u-lg-mgVlg {
		margin-bottom: var(--blank-space-lg) !important;
		margin-top: var(--blank-space-lg) !important;
	}

	.blank-u-lg-mgVgg {
		margin-bottom: var(--blank-space-gg) !important;
		margin-top: var(--blank-space-gg) !important;
	}

	.blank-u-lg-pdVn {
		padding-bottom: var(--blank-space-n) !important;
		padding-top: var(--blank-space-n) !important;
	}

	.blank-u-lg-pdVbb {
		padding-bottom: var(--blank-space-bb) !important;
		padding-top: var(--blank-space-bb) !important;
	}

	.blank-u-lg-pdVsm {
		padding-bottom: var(--blank-space-sm) !important;
		padding-top: var(--blank-space-sm) !important;
	}

	.blank-u-lg-pdVmd {
		padding-bottom: var(--blank-space-md) !important;
		padding-top: var(--blank-space-md) !important;
	}

	.blank-u-lg-pdVlg {
		padding-bottom: var(--blank-space-lg) !important;
		padding-top: var(--blank-space-lg) !important;
	}

	.blank-u-lg-pdVgg {
		padding-bottom: var(--blank-space-gg) !important;
		padding-top: var(--blank-space-gg) !important;
	}

}

@media(--gg) {
	.blank-u-gg-mgVn {
		margin-bottom: var(--blank-space-n) !important;
		margin-top: var(--blank-space-n) !important;
	}

	.blank-u-gg-mgVbb {
		margin-bottom: var(--blank-space-bb) !important;
		margin-top: var(--blank-space-bb) !important;
	}

	.blank-u-gg-mgVsm {
		margin-bottom: var(--blank-space-sm) !important;
		margin-top: var(--blank-space-sm) !important;
	}

	.blank-u-gg-mgVmd {
		margin-bottom: var(--blank-space-md) !important;
		margin-top: var(--blank-space-md) !important;
	}

	.blank-u-gg-mgVlg {
		margin-bottom: var(--blank-space-lg) !important;
		margin-top: var(--blank-space-lg) !important;
	}

	.blank-u-gg-mgVgg {
		margin-bottom: var(--blank-space-gg) !important;
		margin-top: var(--blank-space-gg) !important;
	}

	.blank-u-gg-pdVn {
		padding-bottom: var(--blank-space-n) !important;
		padding-top: var(--blank-space-n) !important;
	}

	.blank-u-gg-pdVbb {
		padding-bottom: var(--blank-space-bb) !important;
		padding-top: var(--blank-space-bb) !important;
	}

	.blank-u-gg-pdVsm {
		padding-bottom: var(--blank-space-sm) !important;
		padding-top: var(--blank-space-sm) !important;
	}

	.blank-u-gg-pdVmd {
		padding-bottom: var(--blank-space-md) !important;
		padding-top: var(--blank-space-md) !important;
	}

	.blank-u-gg-pdVlg {
		padding-bottom: var(--blank-space-lg) !important;
		padding-top: var(--blank-space-lg) !important;
	}

	.blank-u-gg-pdVgg {
		padding-bottom: var(--blank-space-gg) !important;
		padding-top: var(--blank-space-gg) !important;
	}

}
```

output:

```
lib/vertical.css
3:1     Invalid utility selector ".blank-u-mgVn" (selector-bem-pattern)
8:1     Invalid utility selector ".blank-u-mgVbb" (selector-bem-pattern)
13:1    Invalid utility selector ".blank-u-mgVsm" (selector-bem-pattern)
18:1    Invalid utility selector ".blank-u-mgVmd" (selector-bem-pattern)
23:1    Invalid utility selector ".blank-u-mgVlg" (selector-bem-pattern)
28:1    Invalid utility selector ".blank-u-mgVgg" (selector-bem-pattern)
33:1    Invalid utility selector ".blank-u-pdVn" (selector-bem-pattern)
38:1    Invalid utility selector ".blank-u-pdVbb" (selector-bem-pattern)
43:1    Invalid utility selector ".blank-u-pdVsm" (selector-bem-pattern)
48:1    Invalid utility selector ".blank-u-pdVmd" (selector-bem-pattern)
53:1    Invalid utility selector ".blank-u-pdVlg" (selector-bem-pattern)
58:1    Invalid utility selector ".blank-u-pdVgg" (selector-bem-pattern)
64:2    Invalid utility selector ".blank-u-bb-mgVn" (selector-bem-pattern)
69:2    Invalid utility selector ".blank-u-bb-mgVbb" (selector-bem-pattern)
74:2    Invalid utility selector ".blank-u-bb-mgVsm" (selector-bem-pattern)
79:2    Invalid utility selector ".blank-u-bb-mgVmd" (selector-bem-pattern)
84:2    Invalid utility selector ".blank-u-bb-mgVlg" (selector-bem-pattern)
89:2    Invalid utility selector ".blank-u-bb-mgVgg" (selector-bem-pattern)
94:2    Invalid utility selector ".blank-u-bb-pdVn" (selector-bem-pattern)
99:2    Invalid utility selector ".blank-u-bb-pdVbb" (selector-bem-pattern)
104:2   Invalid utility selector ".blank-u-bb-pdVsm" (selector-bem-pattern)
109:2   Invalid utility selector ".blank-u-bb-pdVmd" (selector-bem-pattern)
114:2   Invalid utility selector ".blank-u-bb-pdVlg" (selector-bem-pattern)
119:2   Invalid utility selector ".blank-u-bb-pdVgg" (selector-bem-pattern)
126:2   Invalid utility selector ".blank-u-sm-mgVn" (selector-bem-pattern)
131:2   Invalid utility selector ".blank-u-sm-mgVbb" (selector-bem-pattern)
136:2   Invalid utility selector ".blank-u-sm-mgVsm" (selector-bem-pattern)
141:2   Invalid utility selector ".blank-u-sm-mgVmd" (selector-bem-pattern)
146:2   Invalid utility selector ".blank-u-sm-mgVlg" (selector-bem-pattern)
151:2   Invalid utility selector ".blank-u-sm-mgVgg" (selector-bem-pattern)
156:2   Invalid utility selector ".blank-u-sm-pdVn" (selector-bem-pattern)
161:2   Invalid utility selector ".blank-u-sm-pdVbb" (selector-bem-pattern)
166:2   Invalid utility selector ".blank-u-sm-pdVsm" (selector-bem-pattern)
171:2   Invalid utility selector ".blank-u-sm-pdVmd" (selector-bem-pattern)
176:2   Invalid utility selector ".blank-u-sm-pdVlg" (selector-bem-pattern)
181:2   Invalid utility selector ".blank-u-sm-pdVgg" (selector-bem-pattern)
189:2   Invalid utility selector ".blank-u-md-mgVn" (selector-bem-pattern)
194:2   Invalid utility selector ".blank-u-md-mgVbb" (selector-bem-pattern)
199:2   Invalid utility selector ".blank-u-md-mgVsm" (selector-bem-pattern)
204:2   Invalid utility selector ".blank-u-md-mgVmd" (selector-bem-pattern)
209:2   Invalid utility selector ".blank-u-md-mgVlg" (selector-bem-pattern)
214:2   Invalid utility selector ".blank-u-md-mgVgg" (selector-bem-pattern)
219:2   Invalid utility selector ".blank-u-md-pdVn" (selector-bem-pattern)
224:2   Invalid utility selector ".blank-u-md-pdVbb" (selector-bem-pattern)
229:2   Invalid utility selector ".blank-u-md-pdVsm" (selector-bem-pattern)
234:2   Invalid utility selector ".blank-u-md-pdVmd" (selector-bem-pattern)
239:2   Invalid utility selector ".blank-u-md-pdVlg" (selector-bem-pattern)
244:2   Invalid utility selector ".blank-u-md-pdVgg" (selector-bem-pattern)
252:2   Invalid utility selector ".blank-u-lg-mgVn" (selector-bem-pattern)
257:2   Invalid utility selector ".blank-u-lg-mgVbb" (selector-bem-pattern)
262:2   Invalid utility selector ".blank-u-lg-mgVsm" (selector-bem-pattern)
267:2   Invalid utility selector ".blank-u-lg-mgVmd" (selector-bem-pattern)
272:2   Invalid utility selector ".blank-u-lg-mgVlg" (selector-bem-pattern)
277:2   Invalid utility selector ".blank-u-lg-mgVgg" (selector-bem-pattern)
282:2   Invalid utility selector ".blank-u-lg-pdVn" (selector-bem-pattern)
287:2   Invalid utility selector ".blank-u-lg-pdVbb" (selector-bem-pattern)
292:2   Invalid utility selector ".blank-u-lg-pdVsm" (selector-bem-pattern)
297:2   Invalid utility selector ".blank-u-lg-pdVmd" (selector-bem-pattern)
302:2   Invalid utility selector ".blank-u-lg-pdVlg" (selector-bem-pattern)
307:2   Invalid utility selector ".blank-u-lg-pdVgg" (selector-bem-pattern)
315:2   Invalid utility selector ".blank-u-gg-mgVn" (selector-bem-pattern)
320:2   Invalid utility selector ".blank-u-gg-mgVbb" (selector-bem-pattern)
325:2   Invalid utility selector ".blank-u-gg-mgVsm" (selector-bem-pattern)
330:2   Invalid utility selector ".blank-u-gg-mgVmd" (selector-bem-pattern)
335:2   Invalid utility selector ".blank-u-gg-mgVlg" (selector-bem-pattern)
340:2   Invalid utility selector ".blank-u-gg-mgVgg" (selector-bem-pattern)
345:2   Invalid utility selector ".blank-u-gg-pdVn" (selector-bem-pattern)
350:2   Invalid utility selector ".blank-u-gg-pdVbb" (selector-bem-pattern)
355:2   Invalid utility selector ".blank-u-gg-pdVsm" (selector-bem-pattern)
360:2   Invalid utility selector ".blank-u-gg-pdVmd" (selector-bem-pattern)
365:2   Invalid utility selector ".blank-u-gg-pdVlg" (selector-bem-pattern)
370:2   Invalid utility selector ".blank-u-gg-pdVgg" (selector-bem-pattern)
npm ERR! Test failed.  See above for more details.
```
